"use client";

"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "motion/react";
import { ArrowDownRight, ArrowRight, ArrowUpRight, FileImage, Palette, Sparkles } from "lucide-react";
import { StudioFooter, StudioHeader, studioImages } from "./StudioShell";
import CreativeWorkflowShowcase from "./CreativeWorkflowShowcase";

function FlowLines() {
  return <svg className="studio-flow-lines" viewBox="0 0 1200 520" aria-hidden="true" preserveAspectRatio="none"><path d="M80 130 C 320 40, 410 210, 610 170 S 920 60, 1120 150" /><path d="M80 385 C 290 470, 420 295, 630 330 S 950 470, 1120 340" /><circle cx="80" cy="130" r="5" /><circle cx="610" cy="170" r="5" /><circle cx="1120" cy="150" r="5" /><circle cx="80" cy="385" r="5" /><circle cx="630" cy="330" r="5" /><circle cx="1120" cy="340" r="5" /></svg>;
}

export default function StudioLanding() {
  return <main className="studio-site">
    <StudioHeader />
    <section className="studio-hero studio-starfield"><div className="studio-shell studio-hero__grid"><div className="studio-hero__copy"><p className="studio-kicker"><span className="studio-pulse" /> STUDIO / CREATIVE SYSTEM 01</p><h1>Make the work<br /><em>move.</em></h1><p className="studio-hero__lede">One expressive workspace for the prompts, visuals, captions, and campaigns that make a brand feel alive.</p><div className="studio-hero__actions"><Link href="/register" className="studio-button studio-button--lime studio-button--large">Go to Studio <ArrowUpRight size={17} /></Link><Link href="/contact" className="studio-button studio-button--outline studio-button--large">Talk to sales</Link></div><div className="studio-hero__meta"><span><strong>01</strong> Brief in</span><span><strong>02</strong> Make more</span><span><strong>03</strong> Ship on time</span></div></div><motion.div className="studio-hero__visual" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><div className="studio-hero-card"><Image src={studioImages.hero} alt="STUDIO creative canvas" fill priority sizes="(max-width: 900px) 100vw, 58vw" className="studio-media" /></div><div className="studio-float-card studio-float-card--top"><span>Signal / 004</span><strong>visual direction</strong><b><Sparkles size={13} /> ready</b></div><div className="studio-float-card studio-float-card--bottom"><span>LIVE WORKSPACE</span><strong>12 variations</strong><b><span className="studio-dot studio-dot--lime" /> moving</b></div></motion.div></div><div className="studio-shell studio-hero__footer"><span>Purpose-built tools for every step of your process.</span><span className="studio-scroll-note">Scroll to trace the system <ArrowDownRight size={16} /></span></div></section>

    <section className="studio-constellation studio-starfield"><FlowLines /><div className="studio-shell studio-constellation__intro"><p className="studio-kicker">THE WORKFLOW IS THE PRODUCT</p><h2>From loose thought<br />to <em>living output.</em></h2><p>STUDIO turns the invisible middle of creative work into a visible, connected system.</p></div><motion.div className="studio-node studio-node--brief" whileHover={{ y: -8 }}><span className="studio-node__label">01 / INPUT</span><strong>The brief</strong><p>“Make it feel like summer, but smarter.”</p><div className="studio-node__line"><span className="studio-avatar">A</span> aisha / creative lead</div></motion.div><motion.div className="studio-node studio-node--visual" whileHover={{ y: -8 }}><span className="studio-node__label">02 / OUTPUT</span><Image src={studioImages.model} alt="Editorial model visual" width={420} height={500} className="studio-node__image" /><div className="studio-node__line"><span>model / campaign 04</span><b>approved</b></div></motion.div><motion.div className="studio-node studio-node--caption" whileHover={{ y: -8 }}><span className="studio-node__label">03 / LANGUAGE</span><strong>Context, not filler.</strong><p>“The everyday, with a little more intention.”</p><div className="studio-node__tags"><span>EN</span><span>FR</span><span>AR</span></div></motion.div><div className="studio-constellation__note"><span>∞</span><p>One source of truth<br />for every variation.</p></div></section>

    <section className="studio-light-section"><div className="studio-shell studio-section-heading"><div><p className="studio-kicker studio-kicker--dark">A TOOLKIT FOR THE WHOLE MOTION</p><h2>Small teams.<br /><em>More surface area.</em></h2></div><p>Build the system once. Let the system keep the work moving.</p></div><div className="studio-shell studio-feature-grid">{[["01", "Generate", "Turn a single direction into a considered visual family.", Sparkles], ["02", "Translate", "Keep the tone intact across language, format, and market.", FileImage], ["03", "Compose", "Give every campaign a point of view before it becomes a post.", Palette], ["04", "Publish", "Move from approved to out there without losing the thread.", ArrowUpRight]].map(([index, title, text, Icon]) => { const FeatureIcon = Icon as typeof Sparkles; return <motion.article key={String(index)} className="studio-feature-card" whileHover={{ y: -6 }}><span>{String(index)}</span><FeatureIcon size={19} /><h3>{String(title)}</h3><p>{String(text)}</p><Link href="/features">Explore the system <ArrowRight size={14} /></Link></motion.article>; })}</div></section>

    <section className="studio-demo studio-starfield"><div className="studio-shell studio-demo__grid"><div><p className="studio-kicker">LIVE PREVIEW / MODEL RUNNING</p><h2>Make once.<br /><em>Keep going.</em></h2><p>Every prompt becomes a visual thread. Every thread can become a campaign.</p><Link href="/register" className="studio-button studio-button--lime">Start creating <ArrowUpRight size={15} /></Link></div><div className="studio-demo__screen"><div className="studio-demo__toolbar"><span><span className="studio-dot studio-dot--lime" /> Model running</span><span>Draft / 004</span></div><div className="studio-demo__image"><Image src={studioImages.hero} alt="Creative generation preview" fill sizes="(max-width: 900px) 100vw, 52vw" className="studio-media" /></div><div className="studio-demo__caption"><span>Campaign direction / Summer 26</span><b>4 outputs ready</b></div></div></div></section>
    <CreativeWorkflowShowcase />
    <section className="studio-cta"><div className="studio-shell studio-cta__inner"><div><p className="studio-kicker studio-kicker--dark">THE NEXT DRAFT STARTS HERE</p><h2>Give the work<br /><em>some room.</em></h2></div><Link href="/register" className="studio-button studio-button--dark studio-button--large">Open STUDIO <ArrowUpRight size={17} /></Link></div></section>
    <StudioFooter />
  </main>;
}
